version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: num-bigint
    versions:
    - 0.3.1
    - 0.3.2
  - dependency-name: proptest
    versions:
    - 0.10.1
